== AsciidoctorJ Base Plugin

This plugin is automatically applied by all AsciidoctorJ-based plugins.

Adds an extension for configuring which version of {asciidoctorj-name} and various other {asciidoctorj-name} backends.

This is very much similar to the one used in older versions of the {plugin-name}, but now it also offers the ability to add the same functionality to a task thus allowing a task to override the default versions that has been set.

[source,groovy]
----
asciidoctorj {
  version = '1.5.6' // <1>
  groovyDslVersion = '1.0.0.Alpha2' // <2>

  options doctype: 'book', ruby: 'erubis' // <3>

  attributes toclevel : 2 // <4>
}
----
<1> Set the default version of {asciidoctorj-name} for all Asciidoctor tasks in a project.
<2> Set the default version of the Groovy extensions DSL for all Asciidoctor tasks in a project.
<3> Add options for all Asciidoctor tasks
<4> Add attributes for all Asciidoctor tasks

You can also override or extend select settings within a task using the same extension i.e.

[source,groovy]
----
asciidoctor {
  asciidoctorj {
      setOptions = [ doctype: 'article' ] // <1>

      attributes toc : left // <2>
  }
}
----
<1> Override any global options
<2> Use these attributes in addition to the globally specified ones.

The entities that can be set are:

[horizontal]
attributes:: {asciidoctorj-name} attributes.
  Use `attributes` to append and `setAttributes` to replace any current attributes with a new set.
  Attribute values are lazy-evaluated to strings.
attributesForLang:: Language-specific attributes.
  Specify additional attributes which will only be added if a  source set for the specified language is being processed.
docExtensions:: Groovy DSL extensions.
  Use `docExtensions` to add one or more extensions. Use `setDocExtensions` to replace the current set of extensions with a new set.
  Extensions can be any kind of object that is serialisable, although in most cases they will be strings or files.
  If extensions are detached dependencies, they will not be serialised, but rather will be placed on the classpath in
  order that {asciidoctorj-name} can pick them up automatically.
fatalWarnings:: Patterns for {asciidoctorj-name} log messages that should be treated as fatal errors.
  The list is empty be default. Use `setFatalWarnings` to clear any existing patterns or to decouple a task's configuration from the global
  configuration. Use `fatalWarnings` to add more patterns. Pass `missingIncludes()` to add the common use-case of
  missing include files.
gemPaths:: One or more gem installation directories (separated by the system path separator).
  Use `gemPaths` to append. Use `setGemPaths` or `gemPaths=['path1','path2']` to overwrite.
  Use `asGemPath` to obtain a path string, separated by platform-specific separator.
  Type: FileCollection, but any collection of objects convertible with `project.files` can be passed
  Default: empty
jrubyVersion:: Minimum version of JRuby to be used.
  The exact version that will be used could be higher due to {asciidoctorj-name} having a transitive dependency that is newer.
logLevel:: The log level at which AsciidoctorJ will log.
  This is specified as a Gradle logging level. The plugin will translate it to the appropriate AsciidoctorJ logging level.
  Default is `project.logger.level`.
modules:: Configuration for version of specific compoenents and converters that can be used.
options:: {asciidoctorj-name} options.
  Use `options` to append and `setOptions` to replace any current options with a new set.
  Options are evaluated as late as possible.
requires:: The set of Ruby modules to be included.
  Use `requires` to append. Use `setRequires` or `requires=['name']` to overwrite.
  Default: empty.
resolutionStrategy:: Strategies for resolving Asciidoctorj-related dependencies.
  Asciidoctor dependencies are held in a detached configuration. If for some special reason, you need to modify the way the dependency set is resolved, you can modify the behaviour by adding one or more strategies.
safeMode:: {asciidoctorj-name} safe mode.
  Set the Safe mode as either `UNSAFE`, `SAFE`, `SERVER`, `SECURE`.
  Can be a number (0, 1, 10, 20), a string, or the entity name
version:: Asciidoctorj version.
  If not specified a version will be used.

=== Options & Attributes

The following options may be set using the extension's `options` property

 * header_footer - boolean
 * template_dirs - List<String>
 * template_engine - String
 * doctype - String

Any key/values set on `attributes` is sent as is to Asciidoctor. You may use this Map to specify
a stylesheet for example. The following snippet shows a sample configuration defining attributes.

[source,groovy]
.build.gradle
----
asciidoctorj { <1>
    options doctype: 'book', ruby: 'erubis'

    attributes 'source-highlighter': 'coderay',
                toc                 : '',
                idprefix            : '',
                idseparator         : '-'
}
----
<1> This can be globally on the project extension or locally on the task's extension.

Or in the {kotlindsl}:

[source,kotlin]
.build.gradle.kts
----
tasks {
  "asciidoctor"(AsciidoctorTask::class) { <1>
    options(mapOf("doctype" to "book", "ruby" to "erubis"))

    attributes(
      mapOf(
        "source-highlighter" to "coderay",
        "toc"                to "",
        "idprefix            to "",
        "idseparator"        to "-"
      )
    )
  }
}
----
<1> This is an example of setting it on the task extension in Kotlin.

The following attributes are automatically set by the `asciidoctorj` extension:

 * project-name : matches `$project.name`
 * project-version: matches `$project.version` (if defined). Empty String value if undefined
 * project-group: matches `$project.group` (if defined). Empty String value if undefined

These attributes may be overridden by explicit user input.

You may need to include extra content into the head of the exported document.
For example, you might want to include jQuery inside the `<head>` element of the HTML export.
To do so, first create a docinfo file `src/docs/asciidoc/docinfo.html` containing the content to include, in this case the `<script>` tag to load jQuery.

[source,html]
.src/docs/asciidoc/docinfo.html
----
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.js"></script>
----

Then, add the `docinfo1` attribute to the attributes list in the previous example:

[source,groovy]
.build.gradle
----
attributes docinfo1: ''
----

Refer to the {asciidoctor-docs}[Asciidoctor documentation] to learn more about these options and attributes.

.Note

Attribute values defined on the build file will win over values defined on the documents themselves. You can change
this behavior by appending an `@` at the end of the value when defined in the build file. Please refer to
link:http://asciidoctor.org/docs/user-manual/#attribute-assignment-precedence[Attribute assignment precedence, window="_blank"]
for more information.

=== Versions of components

The modules block currently supports four elements

[source,groovy]
.build.gradle
----
asciidoctorj {
  modules {
    pdf { // <1>
      version '1.2.3'
    }
    epub { // <2>
      version '1.2.3'
    }
    diagram { // <3>
      version '1.2.3'
    }
    groovyDsl { // <4>
      version '1.2.3'
    }
  }
}
----
<1> {asciidoctorj-epub-name} version. If not specified asciidoctorj-epub will not be on the classpath. If you plan to use the EPUB backend and not using the EPUB plugin, then you need to set a version here.
<2> {asciidoctorj-pdf-name} version. If not specified asciidoctorj-pdf will not be on the classpath. If you plan to use the PDF backend and not using the PDF plugin, then you need to set a version here.
<3> See <<diagram,AsciidoctorJ Diagram>>,
<4> Version of Groovy Extensions DSL. If not specified and no extensions are specified, Groovy DSL will not be used. However, if any extensions are added without setting an explicit version and default version will be used.


When using the {kotlin-dsl} the same settings can be achieved use something similar `getModules().getPdf().version("1.2.3")`. In a similar fashion shortcuts can be achived in the {groovy-dsl}:

[source,groovy]
----
asciidoctorj {
  modules {
    pdf.version '1.2.3'
  }

  modules.pdf.version '1.2.3'
}
----

=== Applying the {asciidoctorj-name} Base plugin on its own

If none of the default conventions work for you, the base plugin can be applied on its own.

[source,groovy,role="primary"]
[subs=attributes+]
.build.gradle
----
plugins {
    id 'org.asciidoctor.jvm.base' version '{revnumber}'
}
----

[source,kotlin,role="secondary"]
[subs=attributes+]
.build.gradle.kts
----
plugins {
    id("org.asciidoctor.jvm.base") version "{revnumber}"
}
----