version: 2
registries:
    gradle-plugin-portal:
        type: maven-repository
        url: https://plugins.gradle.org/m2
        username: dummy # Required by dependabot
        password: dummy # Required by dependabot
updates:
    # Plugin Updates
    - package-ecosystem: "gradle"
      directory: "/"
      target-branch: "development-3.x"
      registries:
          - gradle-plugin-portal
      schedule:
          interval: "weekly"
      open-pull-requests-limit: 10
    # Dependency Updates
    - package-ecosystem: "gradle"
      directory: "/"
      target-branch: "development-3.x"
      schedule:
          interval: "weekly"
      open-pull-requests-limit: 10
