plugins {
    id 'org.asciidoctor.internal.model5.gradle.project'
}

agProject {
    configurePlugin(
            'org.asciidoctor.core.base',
            'Asciidoctor Core Base Plugin',
            'Forms the core of all Asciidoctor plugins',
            'org.asciidoctor.gradle.model5.core.plugins.AsciidoctorCoreBasePlugin',
            []
    )
    configurePlugin(
            'org.asciidoctor.core',
            'Asciidoctor Core Plugin',
            'Registers a default publication along with the asciidocAll task',
            'org.asciidoctor.gradle.model5.core.plugins.AsciidoctorCorePlugin',
            []
    )
    configurePlugin(
            'org.asciidoctor.themes',
            'Asciidoctor Themes management plugin',
            'Manages themes for for various ASciidoctor backends',
            'org.asciidoctor.gradle.model5.core.plugins.AsciidoctorCoreThemesPlugin',
            []
    )
}

dependencies {
    compileOnly(project(':asciidoctoreditorconfig'))
}
