plugins {
    id 'org.asciidoctor.internal.model5.gradle.project'
}

agProject {
    configurePlugin(
            'org.asciidoctor.core',
            'Asciidoctor Core Plugin',
            'Forms the core of all Asciidoctor plugins',
            'org.asciidoctor.gradle.model5.core.plugins.AsciidoctorCorePlugin',
            []
    )
}

tasks.named('pluginUnderTestMetadata', PluginUnderTestMetadata) {
    pluginClasspath.from(sourceSets.getByName('testFixtures').runtimeClasspath)
}