/*
 * Copyright 2013-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and`
 * limitations under the License.
 */

// Works around missing 4.0.1 of grgit-core.
buildscript {
    dependencies {
        classpath 'org.ajoberstar.grgit:grgit-core:4.1.1'
    }
}

plugins {
    id 'org.asciidoctor.internal.root'
    id 'net.nemerosa.versioning' version '2.15.1' apply false
    id 'com.github.ben-manes.versions' version '0.50.0' apply false
    id 'com.github.kt3k.coveralls' version '2.12.2' apply false
    id 'net.ossindex.audit' version '0.4.11' apply false
    id 'org.kordamp.jdeps' version '0.2.0' apply false
//    id 'fi.linuxbox.download.worker' version '0.4' apply false
    id 'org.ysb33r.cloudci' version '4.0.0' apply false
    id 'idea'

    id 'org.ysb33r.ivypot'
    id 'org.ysb33r.os' apply false
    id 'org.ysb33r.jruby.resolver' apply false
}

import org.gradle.util.GradleVersion
import java.text.SimpleDateFormat

repositories {
    mavenCentral()
}

ivypot {
    projectsWithDependencies { it.startsWith(':asciidoctor-gradle-') || it ==~ /^:asciidoctor5-.+-plugin$/ }

    binaryRepositories {
        source 'nodejs', {
            rootUri = 'https://nodejs.org/dist/'
            artifactPattern = 'v[revision]/[module]-v[revision]-[classifier].[ext]'
        }
    }
}

apply plugin: 'net.nemerosa.versioning'

ext {
    buildTimeAndDate = new Date()
    buildDate = new SimpleDateFormat('yyyy-MM-dd').format(buildTimeAndDate)
    buildTime = new SimpleDateFormat('HH:mm:ss.SSSZ').format(buildTimeAndDate)
    buildRevision = versioning.info.commit
    buildCreatedBy = "${System.properties['java.version']} (${System.properties['java.vendor']} ${System.properties['java.vm.version']})".toString()
}
//
//allprojects {
//    ext {
//        withoutIntegrationTests = [
//            'kindlegen-gradle'
//        ]
//
//        withoutCompatibilityTests = [
//            'kindlegen-gradle'
//        ]
//
//        withoutCodeCoverage = [
//        ]
//    }
//}


// ********* TEMPORARY FOR LOCAL DEV
//tasks.named('syncRemoteRepositories') { enabled = false }