version=5.0.0-alpha.2.0
group=org.asciidoctor
projectInceptionYear=2013
project_description=A Gradle plugin suite that uses Asciidoctor via JRuby/Node.js to process AsciiDoc source files within the project.
project_website=https://github.com/asciidoctor/asciidoctor-gradle-plugin
project_issues=https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues
project_vcs=https://github.com/asciidoctor/asciidoctor-gradle-plugin.git
minGradle=8.0.2
otherGradleTestVersions=8.9,8.14.3
jdkVersion=8
jdkVersionAsciidoctorj=11
#####################
org.gradle.caching=true
org.gradle.parallel=false
org.gradle.jvmargs=-Xmx3g -XX\:MaxMetaspaceSize=2g
#####################
# These are versions other than the default version
jrubyTestVersions=9.4.0.0,9.4.1.0,9.4.8.0,9.4.14.0,10.0.2.0
#####################



