version=5.0.0-alpha.1-SNAPSHOT
group=org.asciidoctor
projectInceptionYear=2013
project_description=A Gradle plugin suite that uses Asciidoctor via JRuby/Node.js to process AsciiDoc source files within the project.
project_website=https://github.com/asciidoctor/asciidoctor-gradle-plugin
project_issues=https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues
project_vcs=https://github.com/asciidoctor/asciidoctor-gradle-plugin.git
minGradle=8.0.2
otherGradleTestVersions=8.9,8.14.3
jdkVersion=8
jdkVersionAsciidoctorj=11
#####################
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx3g -XX\:MaxMetaspaceSize=2g
#####################
# These are versions other than the default version
jrubyTestVersions=9.2.5.0,9.3.8.0,9.4.0.0
#####################

#cglibVersion=3.3.0
#jsoupVersion=1.17.2
#spockVersion=2.3-groovy-3.0
##grolifantVersion       = 5.0.0
#jacocoVersion=0.8.6
#codenarcVersion=3.3.0
#nodejsGradleVersion    = 4.0.0-alpha.1
#pluginJrubySimpleVersion = 2.0.0-alpha.4
#pluginPublishPlugin = 1.2.1


