version=6.0.0-milestone.1
group=org.asciidoctor
projectInceptionYear=2013
project_description=A Gradle plugin suite that uses Asciidoctor via JRuby/Node.js to process AsciiDoc source files within the project.
project_website=https://github.com/asciidoctor/asciidoctor-gradle-plugin
project_issues=https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues
project_vcs=https://github.com/asciidoctor/asciidoctor-gradle-plugin.git
minGradle=8.0.2
otherGradleTestVersions=9.0.0,9.1.0,9.7.1,9.8.0
jdkVersion=17
jdkVersionAsciidoctorj=17
#####################
org.gradle.caching=true
org.gradle.parallel=false
org.gradle.jvmargs=-Xmx3g -XX\:MaxMetaspaceSize=2g
#####################
# These are versions other than the default version
jrubyTestVersions=9.4.0.0,9.4.1.0,9.4.8.0,9.4.14.0,10.0.2.0
#####################



