pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        mavenLocal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
    id "com.gradle.develocity" version "3.18.1"
}

develocity {
    buildScan {
        termsOfUseUrl = "https://gradle.com/help/legal-terms-of-use"
        termsOfUseAgree = "yes"
        publishing.onlyIf { System.getenv('CI') != null }
    }
}

rootProject.name = 'asciidoctor-gradle-plugin'

include 'asciidoctoreditorconfig'

// New model5 plugins

['core', 'js-core', 'jvm-core'].each {
    include "model5/${it}"
    project(":model5/${it}").name = "asciidoctor5-${it}-plugin"
}


['jvm'].each {
    include "testfixtures/${it}"
    project(":testfixtures/${it}").name = "testfixtures-${it}"
}

// Deprecated, classic plugins go here
['base', 'jvm', 'js'].each {
    include "classic/${it}"
    project(":classic/${it}").name = "asciidoctor-gradle-${it}"
}
['pdf', 'epub'].each {
    include "classic/jvm-${it}"
    project(":classic/jvm-${it}").name = "asciidoctor-gradle-jvm-${it}"
}
//['gems' /*, 'slides'*/].each {
//    include "classic/${it}"
//    project(":classic/${it}").name = "asciidoctor-gradle-jvm-${it}"
//}

////[  'slides-export' ].each {
////    include "classic/${it}"
////    project(":classic/${it}").name = "asciidoctor-gradle-${it}"
////}
//

