pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
    id "com.gradle.develocity" version "4.1.1"
}

develocity {
    buildScan {
        termsOfUseUrl = "https://gradle.com/help/legal-terms-of-use"
        termsOfUseAgree = "yes"
        publishing.onlyIf { System.getenv('CI') != null }
    }
}

rootProject.name = 'asciidoctor-gradle-plugin'

include 'asciidoctoreditorconfig'
project(":asciidoctoreditorconfig").projectDir = file("model5/asciidoctoreditorconfig")

['core', 'js-core', 'jvm-core', 'downdoc'].each {
    include "model5/${it}"
    project(":model5/${it}").name = "asciidoctor5-${it}-plugin"
}


['jvm'].each {
    include "testfixtures/${it}"
    project(":testfixtures/${it}").name = "testfixtures-${it}"
}

include 'test-all-model5-plugins'

