plugins {
    id 'org.asciidoctor.internal.model5.gradle.project.jvm'
}

// tag::hacking-asciidoctorj-output-formatter[]
agProject {
    // end::hacking-asciidoctorj-output-formatter[]
    withJdkVersionFromProperty('jdkVersionAsciidoctorj')
    withIntegrationTests()
    withOfflineCacheConfiguration()

    configurePlugin(
            'org.asciidoctor.jvm.base',
            'AsciidoctorJ Base Plugin',
            'Base plugin for all AsciidoctorJ tasks & extensions.',
            'org.asciidoctor.gradle.model5.jvm.plugins.AsciidoctorjBasePlugin',
            ['asciidoctorj']
    )

    configurePlugin(
            'org.asciidoctor.jvm',
            'AsciidoctorJ Plugin',
            'Provides html and docbook formatters for all AsciidoctorJ toolchains',
            'org.asciidoctor.gradle.model5.jvm.plugins.AsciidoctorjPlugin',
            ['asciidoctorj']
    )

    configurePlugin(
            'org.asciidoctor.jvm.pdf',
            'AsciidoctorJ Pdf Plugin',
            'Provides pdf formatters for all AsciidoctorJ toolchains',
            'org.asciidoctor.gradle.model5.jvm.plugins.AsciidoctorjPdfPlugin',
            ['asciidoctorj', 'pdf']
    )

    configurePlugin(
            'org.asciidoctor.jvm.revealjs',
            'AsciidoctorJ Reveal.js Plugin',
            'Provides Reveal.js formatters for all AsciidoctorJ toolchains',
            'org.asciidoctor.gradle.model5.jvm.plugins.AsciidoctorjRevealjsPlugin',
            ['asciidoctorj', 'revealjs']
    )

    // tag::hacking-asciidoctorj-output-formatter[]
    configurePlugin(
            'org.asciidoctor.jvm.epub', // <.>
            'AsciidoctorJ EPUB Plugin', // <.>
            'Provides EPUB formatters for all AsciidoctorJ toolchains', // <.>
            'org.asciidoctor.gradle.model5.jvm.plugins.AsciidoctorjEpubPlugin', // <.>
            ['asciidoctorj', 'epub', 'epub3'] // <.>
    )
    // end::hacking-asciidoctorj-output-formatter[]

    // tag::hacking-asciidoctorj-output-formatter[]
    withVersionSubstitution("${project.name}.properties", [
            // end::hacking-asciidoctorj-output-formatter[]
            BATIK    : versionOf('asciidoctorjDiagramBatik'),
            DIAGRAM  : versionOf('asciidoctorjDiagram'),
            DITAA    : versionOf('asciidoctorjDiagramDitaa'),
            // tag::hacking-asciidoctorj-output-formatter[]
            EPUB     : versionOf('asciidoctorjEpub'), // <.>
            // end::hacking-asciidoctorj-output-formatter[]
            GROOVYDSL: versionOf('asciidoctorjGroovyDsl'),
            JSYNTRAX : versionOf('asciidoctorjDiagramJSyntrax'),
            PDF      : versionOf('asciidoctorjPdf'),
            PLANTUML : versionOf('asciidoctorjDiagramPlantUml'),
            REVEALJS : versionOf('asciidoctorjRevealjs'),
            VERSION  : versionOf('asciidoctorj'),
            // tag::hacking-asciidoctorj-output-formatter[]
    ])
    // end::hacking-asciidoctorj-output-formatter[]

// tag::hacking-asciidoctorj-output-formatter[]
}
// end::hacking-asciidoctorj-output-formatter[]

// tag::hacking-asciidoctorj-output-formatter[]
dependencies {
    // end::hacking-asciidoctorj-output-formatter[]
    compileOnly(libs.asciidoctorjApi)
    api project(':asciidoctor5-core-plugin')
    implementation(libs.grolifantApi)
    runtimeOnly(libs.grolifantRuntime)
    testImplementation project(':testfixtures-jvm')

    cachingOnly(libs.asciidoctorjPdf)
    cachingOnly(libs.asciidoctorjDiagram)
    cachingOnly(libs.asciidoctorjDiagramBatik)
    cachingOnly(libs.asciidoctorjDiagramDitaa)
    cachingOnly(libs.asciidoctorjDiagramJSyntrax)
    cachingOnly(libs.asciidoctorjDiagramPlantUml)
    cachingOnly(libs.asciidoctorjRevealjs)

    // tag::hacking-asciidoctorj-output-formatter[]
    cachingOnly(libs.asciidoctorjEpub) // <.>
}
// end::hacking-asciidoctorj-output-formatter[]