plugins {
    id 'org.asciidoctor.internal.model5.gradle.project.jvm'
}

agProject {
    withJdkVersionFromProperty('jdkVersionAsciidoctorj')
    withIntegrationTests()
    withOfflineTestConfigurations()

    configurePlugin(
            'org.asciidoctor.jvm.base',
            'AsciidoctorJ Base Plugin',
            'Base plugin for all AsciidoctorJ tasks & extensions.',
            'org.asciidoctor.gradle.model5.jvm.plugins.AsciidoctorjBasePlugin',
            ['asciidoctorj']
    )

    configurePlugin(
            'org.asciidoctor.jvm',
            'AsciidoctorJ Plugin',
            'Provides html and docbook formatters for all AsciidoctorJ toolchains',
            'org.asciidoctor.gradle.model5.jvm.plugins.AsciidoctorjPlugin',
            ['asciidoctorj']
    )

    configurePlugin(
            'org.asciidoctor.jvm.pdf',
            'AsciidoctorJ Pdf Plugin',
            'Provides pdf formatters for all AsciidoctorJ toolchains',
            'org.asciidoctor.gradle.model5.jvm.plugins.AsciidoctorjPdfPlugin',
            ['asciidoctorj']
    )

    withVersionSubstitution("${project.name}.properties", [
            BATIK    : versionOf('asciidoctorjDiagramBatik'),
            DIAGRAM  : versionOf('asciidoctorjDiagram'),
            DITAA    : versionOf('asciidoctorjDiagramDitaa'),
            GROOVYDSL: versionOf('asciidoctorjGroovyDsl'),
            JSYNTRAX    : versionOf('asciidoctorjDiagramJSyntrax'),
            PDF      : versionOf('asciidoctorjPdf'),
            PLANTUML : versionOf('asciidoctorjDiagramPlantUml'),
            VERSION  : versionOf('asciidoctorj'),
    ])
}

configurations {
    cachingOnly
}

dependencies {
    compileOnly(libs.asciidoctorjApi)
    api project(':asciidoctor5-core-plugin')
    implementation(libs.grolifantApi)
    runtimeOnly(libs.grolifantRuntime)
    testImplementation project(':testfixtures-jvm')

    cachingOnly(libs.asciidoctorjPdf)
    cachingOnly(libs.asciidoctorjDiagram)
    cachingOnly(libs.asciidoctorjDiagramBatik)
    cachingOnly(libs.asciidoctorjDiagramDitaa)
    cachingOnly(libs.asciidoctorjDiagramJSyntrax)
    cachingOnly(libs.asciidoctorjDiagramPlantUml)
}