= Bootstrapping

This describes the plugins for the new Asciidoctor model.
For classic operation see xref:classic/quick-start.adoc[] instead.

== Using versions in build.gradle

[source,groovy,subs=+attributes]
----
plugins {
    id 'org.asciidoctor.jvm' version '{release-version}' // <.>
    id 'org.asciidoctor.jvm.diagram' version '{release-version}' // <.>
    id 'org.asciidoctor.jvm.epub' version '{release-version}' // <.>
    id 'org.asciidoctor.jvm.gems' version '{release-version}' // <.>
    id 'org.asciidoctor.jvm.kroki' version '{release-version}' // <.>
    id 'org.asciidoctor.jvm.pdf' version '{release-version}' // <.>
    id 'org.asciidoctor.jvm.revealjs' version '{release-version}' // <.>
    id 'org.asciidoctor.js' version '{release-version}' // <.>
    id 'org.asciidoctor.js.docbook' version '{release-version}' // <.>
    id 'org.asciidoctor.js.kroki' version '{release-version}' // <.>
    id 'org.asciidoctor.js.revealjs' version '{release-version}' // <.>
}
----
<.> The convention plugin for working with {asciidoctorj-name}.
  Applies `org.asciidoctor.jvm.base` and also creates a default toolchain called `asciidoctorj`.
<.> Registers an extension with support for `asciidoctorj-diagram`.
<.> Registers the output formatter for creating EPUB files.
<.> Adds support for adding additional GEMs to the execution classpath.
<.> Adds the Kroki extension for use with `asciidoctorj` extensions.
<.> Applies `org.asciidoctor.core.pdf-themes` and also registers the output formatter for creating PDF files.
<.> Adds the ability to generate slides with {asciidoctorj-revealjs-name}.
<.> The convention plugin for working with {asciidoctorjs-name}.
  Applies `org.asciidoctor.jvm.base` and also creates a default toolchain called `asciidoctorjs`.
<.> Adds the ability to output to Docbook using {asciidoctorjs-name}.
<.> Adds the Kroki extension for use with `asciidoctorjs` extensions.
<.> Adds the ability to generate slides with {asciidoctorjs-revealjs-name}.

There is also a set of less common plugins, which are applied via the plugins listed above.
They are listed here as they might prove useful in special cases

[source,groovy,subs=+attributes]
----
plugins {
    id 'org.asciidoctor.editorconfig' version '{release-version}' // <.>
    id 'org.asciidoctor.core.base' version '{release-version}' // <.>
    id 'org.asciidoctor.core' version '{release-version}' // <.>
    id 'org.asciidoctor.core.pdf-themes' version '{release-version}' // <.>
    id 'org.asciidoctor.jvm.base' version '{release-version}' // <.>
    id 'org.asciidoctor.js.base' version '{release-version}' // <.>
}
----
<.> Produces an `.asciidoctoreditorconfig` file for IDE purposes.
<.> The Asciidoctor base plugin, which is engine free. Only provides the `asciidoc` extension and the `showAsciidoctorToolchains` task.
<.> The Asciidoctor core plugin, which is engine free. Adds a single publication called `main` and a task called `asciidoctorAll`.
<.> Adds the `asciidocPdfThemes` extension.
<.> Registers the ability to create {asciidoctorj-name} toolchains along with output formatters for HTML, DocBook and Manpages.
  Also registers the diagram {asciidoctorj-name} extension.
<.> Registers the ability to create {asciidoctorjs-name} toolchains along with an HTML output formatter.

== Using the version catalog

.gradle/libs.versions.toml
[source,toml,subs=+attributes]
----
[versions]
asciidoctorPlugin = "{release-version}"

[plugins]
asciidoctorj = { id ="org.asciidoctor.jvm", version.ref = "asciidoctorPlugin" }
asciidoctorjDiagram = { id ="org.asciidoctor.jvm.diagram", version.ref = "asciidoctorPlugin" }
asciidoctorjEpub = { id ="org.asciidoctor.jvm.epub", version.ref = "asciidoctorPlugin" }
asciidoctorjGems = { id ="org.asciidoctor.jvm.gems", version.ref = "asciidoctorPlugin" }
asciidoctorjKroki = { id ="org.asciidoctor.jvm.kroki", version.ref = "asciidoctorPlugin" }
asciidoctorjPdf = { id ="org.asciidoctor.jvm.pdf", version.ref = "asciidoctorPlugin" }
asciidoctorjRevealjs = { id ="org.asciidoctor.jvm.revealjs", version.ref = "asciidoctorPlugin" }
asciidoctorjs = { id ="org.asciidoctor.js", version.ref = "asciidoctorPlugin" }
asciidoctorjsDocbook = { id ="org.asciidoctor.js.docbook", version.ref = "asciidoctorPlugin" }
asciidoctorjsKroki = { id ="org.asciidoctor.js.kroki", version.ref = "asciidoctorPlugin" }
asciidoctorjsRevealjs = { id ="org.asciidoctor.js.reveraljs", version.ref = "asciidoctorPlugin" }
asciidoctorEditorConfig = { id ="org.asciidoctor.editorconfig", version.ref = "asciidoctorPlugin" }
----

.build.gradle
[source,groovy]
----
plugins {
    id alias(libs.plugins.asciidoctorj)
    id alias(libs.plugins.asciidoctorjDiagram)
    id alias(libs.plugins.asciidoctorjEpub)
    id alias(libs.plugins.asciidoctorjGems)
    id alias(libs.plugins.asciidoctorjPdf)
    id alias(libs.plugins.asciidoctorjRevealjs)
    id alias(libs.plugins.asciidoctorjs)
    id alias(libs.plugins.asciidoctorjsDocbook)
    id alias(libs.plugins.asciidoctorjsRevealjs)
    id alias(libs.plugins.asciidoctorEditorConfig)
}
----