plugins {
    id 'org.asciidoctor.internal.model5.gradle.project'
}

agProject {
    withIntegrationTests()
    configurePlugin(
            'org.asciidoctor.js.base',
            'AsciidoctorJS Base Plugin',
            'Base plugin for all AsciidoctorJS tasks & extensions. Provides the asciidoctorjs toolchain',
            'org.asciidoctor.gradle.model5.js.plugins.AsciidoctorJSBasePlugin',
            ['asciidoctorjs']
    )
    configurePlugin(
            'org.asciidoctor.js',
            'AsciidoctorJS Plugin',
            'Provides html formatter for all AsciidoctorJS toolchains',
            'org.asciidoctor.gradle.model5.js.plugins.AsciidoctorjsPlugin',
            ['asciidoctorj']
    )
    configurePlugin(
            'org.asciidoctor.js.docbook',
            'AsciidoctorJS Docbook Plugin',
            'Provides docbook formatter for all AsciidoctorJS toolchains',
            'org.asciidoctor.gradle.model5.js.plugins.AsciidoctorjsDocbookPlugin',
            ['asciidoctorj']
    )

    withVersionSubstitution("${project.name}.properties", [
            VERSION  : versionOf('asciidoctorjs'),
            CLI: versionOf('asciidoctorjsCli'),
            DOCBOOK : versionOf('asciidoctorjsDocbook'),
            EJS: versionOf('asciidoctorjsEjs'),
            HANDLEBARS: versionOf('asciidoctorjsHandlebars'),
            MANPAGE : versionOf('asciidoctorjsManpage'),
            NODE: versionOf('nodejs'),
            NUNJUCKS: versionOf('asciidoctorjsNunjucks'),
            PUG: versionOf('asciidoctorjsPug'),
    ])
}

dependencies {
    api project(':asciidoctor5-core-plugin')
    api(libs.pluginJavaScript)
    implementation(libs.grolifantApi)
    runtimeOnly(libs.grolifantRuntime)
    testImplementation project(':testfixtures-jvm')
}