plugins {
    id 'org.asciidoctor.internal.model5.gradle.project'
}

apply from: "${rootDir}/gradle/cache-node.gradle"

// tag::hacking-asciidoctorjs-output-formatter[]
agProject {
// end::hacking-asciidoctorjs-output-formatter[]
    withIntegrationTests()
    configurePlugin(
        'org.asciidoctor.js.base',
        'Asciidoctor.js Base Plugin',
        'Base plugin for all AsciidoctorJS tasks & extensions. Provides the asciidoctorjs toolchain',
        'org.asciidoctor.gradle.model5.js.plugins.AsciidoctorjsBasePlugin',
        ['asciidoctorjs']
    )
    configurePlugin(
        'org.asciidoctor.js',
        'Asciidoctor.js Plugin',
        'Provides html formatter for all AsciidoctorJS toolchains',
        'org.asciidoctor.gradle.model5.js.plugins.AsciidoctorjsPlugin',
        ['asciidoctorjs']
    )
    configurePlugin(
        'org.asciidoctor.js.docbook',
        'Asciidoctor.js Docbook Plugin',
        'Provides docbook formatter for all AsciidoctorJS toolchains',
        'org.asciidoctor.gradle.model5.js.plugins.AsciidoctorjsDocbookPlugin',
        ['asciidoctorjs', 'docbook']
    )
    configurePlugin(
        'org.asciidoctor.js.kroki',
        'Asciidoctor.js Kroki Plugin',
        'Allows Kroki to be used with all AsciidoctorJS toolchains',
        'org.asciidoctor.gradle.model5.js.plugins.AsciidoctorjsKrokiPlugin',
        ['asciidoctorjs', 'kroki', 'actdiag', 'blockdiag', 'ditaa', 'plantuml',
         'bpmn', 'bytefield', 'c4plantuml', 'd2', 'dbml', 'erd',
         'excalidraw', 'graphviz', 'mermaid', 'nomnoml', 'nwdiag',
         'packetdiag', 'pikchr', 'rackdiag', 'seqdiag', 'svgbob',
         'symbolator', 'umlet', 'vega', 'vegalite', 'wavedrom', 'structurizr'
        ]
    )
    // tag::hacking-asciidoctorjs-output-formatter[]
    configurePlugin(
        'org.asciidoctor.js.revealjs', // <.>
        'Asciidoctor.js Reveal.js Plugin', // <.>
        'Provides Reveal.js formatter for all Asciidoctor.js toolchains', // <.>
        'org.asciidoctor.gradle.model5.js.plugins.AsciidoctorjsRevealjsPlugin', // <.>
        ['asciidoctorjs', 'revealjs', 'slides'] // <.>
    )
    // end::hacking-asciidoctorjs-output-formatter[]


    // tag::hacking-asciidoctorjs-output-formatter[]
    withVersionSubstitution("${project.name}.properties", [
        // end::hacking-asciidoctorjs-output-formatter[]
        VERSION     : versionOf('asciidoctorjs'),
        CLI         : versionOf('asciidoctorjsCli'),
        DOCBOOK     : versionOf('asciidoctorjsDocbook'),
        EJS         : versionOf('asciidoctorjsEjs'),
        HANDLEBARS  : versionOf('asciidoctorjsHandlebars'),
        KROKI       : versionOf('asciidoctorjsKroki'),
        MANPAGE     : versionOf('asciidoctorjsManpage'),
        NODE        : versionOf('nodejs'),
        NODE_WINDOWS: versionOf('nodejsWindows'),
        NUNJUCKS    : versionOf('asciidoctorjsNunjucks'),
        PUG         : versionOf('asciidoctorjsPug'),
        // tag::hacking-asciidoctorjs-output-formatter[]
        REVEALJS    : versionOf('asciidoctorjsRevealjs'), // <.>
        // end::hacking-asciidoctorjs-output-formatter[]
        // tag::hacking-asciidoctorjs-output-formatter[]
    ])
    // end::hacking-asciidoctorjs-output-formatter[]
// tag::hacking-asciidoctorjs-output-formatter[]
}
// end::hacking-asciidoctorjs-output-formatter[]

dependencies {
    api project(':asciidoctor5-core-plugin')
    api(libs.pluginJavaScript)
    implementation(libs.grolifantApi)
    runtimeOnly(libs.grolifantRuntime)
    testImplementation project(':testfixtures-jvm')
}
