plugins {
    id 'org.asciidoctor.internal.classic.gradle.project'
}

agProject {
    withAdditionalPluginClasspath()

    configurePlugin(
            'org.asciidoctor.editorconfig.classic',
            'Asciidoctor Editor Config Plugin (Deprecated)',
            'Generate .asciidoctorconfig files for use by supported IDEs. (Deprecated)',
            'org.asciidoctor.gradle.editorconfig.AsciidoctorEditorConfigPlugin',
            ['intellij', 'idea']
    )
}

dependencies {
    implementation project(':asciidoctor-gradle-base')
}



