plugins {
    id 'org.asciidoctor.internal.classic.gradle.project.jvm'
}

agProject {
    withOfflineTestConfigurations()
    withIntegrationTests()
    withCompatibilityTests()

    configurePlugin(
            'org.asciidoctor.jvm.pdf',
            'AsciidoctorJ PDF Conversion Plugin',
            'Simplifies conversion of asciidoc documents to PDF',
            'org.asciidoctor.gradle.jvm.pdf.AsciidoctorJPdfPlugin',
            ['asciidoctorj', 'pdf']
    )
}

configurations {
    cachingOnly
}

dependencies {
    api project(':asciidoctor-gradle-jvm')
    api(libs.grolifantRemoteWorker)
    intTestOfflineRepo "org.asciidoctor:asciidoctorj:${agProject.versionOf('asciidoctorj')}"
    intTestOfflineRepo "org.asciidoctor:asciidoctorj-pdf:${agProject.versionOf('asciidoctorjPdf')}"

    cachingOnly(libs.asciidoctorjPdf) { transitive = false }
}

tasks.named('test', Test) {
    systemProperties TEST_THEMES_DIR: file('src/test/resources/themes')
}

tasks.named('integrationTest', Test) {
    maxParallelForks = 2
    forkEvery = 1
    maxHeapSize = '2048m'
}

