= Asciidoctor Gradle Plugin Suite
include::attributes.adoc[]
ifdef::env-idea[]
:toc: preamble
endif::[]
ifeval::[{env}!=idea]
:toc: right
endif::[]

The {doctitle} is the official means of using {asciidoctor-url}[Asciidoctor] to convert all your {asciidoc-url}[AsciiDoc] documentation using {gradle-url}[Gradle].

This started as a port of the {asciidoctor-maven-plugin} project founded by {lightguard} and relies on {asciidoctorj}[{asciidoctorj-name}] which was founded by {lordofthejars}. In fact the 1.5.x series of the {plugin-name} can still be considered a port. However with 2.x series came a complete departure with functionality far exceeding any lightweight markup plugins for any other build tool. With the 3.x serious allows for even more flexibility and options for the creation of a true DocuOps pipeline by bringing together Gradle as a powerful and generic build tool, and Asciidoctor as an agile and lightweight document generator.

include::parts/compatibility.adoc[]

include::parts/quick-start.adoc[]

include::parts/common-task-configuration.adoc[]

include::parts/asciidoctorj-base-plugin.adoc[]

include::parts/asciidoctorj-plugin.adoc[]

include::parts/asciidoctorj-pdf-plugin.adoc[]

include::parts/asciidoctorj-epub-plugin.adoc[]

include::parts/asciidoctorj-revealjs-plugin.adoc[]

include::parts/asciidoctorj-leanpub-plugin.adoc[]

include::parts/asciidoctor-diagram.adoc[]

include::parts/asciidoctorj-gems-plugin.adoc[]

include::parts/kindlegen-plugin.adoc[]

include::parts/asciidoctorj-custom-extensions.adoc[]

include::parts/asciidoctorjs-plugin.adoc[]

include::parts/asciidoctoreditorconfig-plugin.adoc[]

include::parts/docinfo.adoc[]

include::parts/upgrading.adoc[]

include::appendix/tips-and-tricks.adoc[]

include::appendix/known-limitations.adoc[]

include::appendix/hacking.adoc[]
