plugins {
    id 'org.asciidoctor.internal.classic.gradle.project.jvm'
}

agProject {
    withClassicOfflineTestConfigurations()
    withIntegrationTests()
    withCompatibilityTests()

    configurePlugin 'org.asciidoctor.jvm.gems.classic',
            'Simplifies support for using external GEMs with AsciidoctorJ (Deprecated)',
            'Provides appropriate tasks and configurations for adding GEMs to AsciidoctorJ conversions (Deprecated)',
            'org.asciidoctor.gradle.jvm.gems.AsciidoctorGemSupportPlugin',
            ['asciidoctorj', 'gems', 'jruby']
}

dependencies {
    implementation(libs.pluginJRuby)
    api project(':asciidoctor-gradle-jvm')
    api (libs.grolifantApi)
}




