= The Reveal.js output formatter

{asciidoctorjs-revealjs-name} is a popular way of creating slides with {asciidoctorjs-name} and is available via the  `org.asciidoctor.js.revealjs` plugin.

There are many items that can be configured on the output formatter itself.

[tabs]
====
Groovy::
+
--
[source,groovy]
----
import org.asciidoctor.gradle.model5.js.formatters.AsciidoctorjsRevealjs

asciidoc {
    toolchains {
        asciidoctorjs3 { // <.>
            registeredOutputFormatters {
                revealjs(AsciidoctorjsRevealjs) { // <.>
                    templateDirs 'src/myAsciidocTemplate1', 'src/myAsciidocTemplate2' // <.>
                    useEngine 'nunjucks' // <.>
                    useEngine 'handlebars', '1.2.3' // <.>
                    revealjsOptions { // <.>
                    }
                }
            }
        }
    }
}
----
<.> Currently, this is only supported for the Opal engine, which is the `asciidoctorjs3` toolchain.
<.> The `org.asciidoctor.js.revealjs` plugin adds an output formatter called `revealjs`.
<.> Define one or more templates that can be used for conversion.
<.> Adds an engine from NPM using the default version.
  Only `ejs`, `handlebars`, `js`, `nunjucks` and `pug` are supported.
  `js` is a NOOP as template-js is a built-in.
<.> Adds an engine from NPM using the specified version.
<.> Configures {asciidoctorjs-revealjs-name} options.
    See below.
--
====

NOTE: `templateDirs` must be provided, otherwise template setting will be ignored.
  It will auto-detect engines from the file extensions found in the template directories.

include::partial$revealjs-options.adoc[]
