plugins {
    id 'org.asciidoctor.internal.classic.module.versions'
    id 'org.asciidoctor.internal.classic.gradle.project'
    id 'org.ysb33r.os'
    id 'org.ysb33r.ivypot'
}

agProject {
    withClassicOfflineTestConfigurations()
    withIntegrationTests()
    withCompatibilityTests()
    configurePlugin(
        'org.asciidoctor.js.base.classic',
        'Asciidoctor.js Classic (Deprecated) Base Plugin',
        'Deprecated base plugin for all Asciidoctor.js tasks & extensions. Provides the asciidoctorjs project extension',
        'org.asciidoctor.gradle.js.nodejs.core.AsciidoctorNodeJSBasePlugin',
        ['asciidoctor.js'],
        false
    )

    configurePlugin(
        'org.asciidoctor.js.convert.classic',
        'Asciidoctor.js Classic (Deprecated) General Purpose Document Conversion Plugin',
        'Deprecated asciidoctor task and convention using the asciidoctor.js engine',
        'org.asciidoctor.gradle.js.nodejs.AsciidoctorNodeJSPlugin',
        ['asciidoctor.js', 'html5', 'docbook'],
        false
    )

    withVersionSubstitution("${project.name}.properties", [
        VERSION: versionOf('asciidoctorjs3'),
        NODE   : versionOf('nodejs')
    ])
}

ext {
    if (OS.windows) {
        nodejsExt = 'zip'
        if (System.getProperty('os.arch').contains('64')) {
            nodejsArch = 'win-x64'
        } else {
            nodejsArch = 'win-x86'
        }
    } else if (OS.linux) {
        nodejsExt = 'tar.xz'
        if (System.getProperty('os.arch').contains('64')) {
            nodejsArch = 'linux-x64'
        } else {
            nodejsArch = 'linux-x86'
        }
    } else if (OS.macOsX) {
        nodejsExt = 'tar.gz'
        nodejsArch = 'darwin-x64'
    }
}

dependencies {
    api(project(':asciidoctor-gradle-base'))
    api(libs.pluginJavaScript)
    api(libs.grolifantApi)
    runtimeOnly(libs.grolifantRuntime)
}

ivypot {
    cacheBinaries.add "nodejs:node:${agProject.versionOf('nodejs')}:${nodejsArch}@${nodejsExt}"
}

generateModuleVersions {
    basename = 'asciidoctorjs-extension'
    propertyNames ~/^asciidoctorjs$/, ~/^asciidoctorjs\./
}

tasks.named('test', Test) {
    systemProperties ROOT_PROJECT_DIR: rootProject.projectDir.absolutePath
}

tasks.withType(Test).configureEach {
    systemProperties 'org.ysb33r.gradle.nodejs.uri': project.uri(new File(rootDir, '.offline-repo/binaries/nodejs'))
}



