/*
 * Copyright 2013 - 2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.asciidoctor.gradle.model5.jvm

import org.asciidoctor.gradle.model5.jvm.testfixtures.AsciidoctorjHtmlIntegrationSpecification

import static org.asciidoctor.gradle.model5.core.internal.publications.PublicationUtils.DEFAULT_PUBLICATION
import static org.gradle.testkit.runner.TaskOutcome.SUCCESS
import static org.gradle.testkit.runner.TaskOutcome.UP_TO_DATE

/**
 * Sources that are produced by another task in the same build.
 *
 * @author Laura Kassovic
 *
 * @since 5.0.2
 */
class GeneratedSourcesSpec extends AsciidoctorjHtmlIntegrationSpecification {

    void setup() {
        writeHtmlBasedBuildFile()
    }

    void 'Sources generated by another task are converted when the configuration cache is enabled'() {
        setup:
        copyTestProject('resources')
        buildFile << '''
        def generateDocs = tasks.register('generateDocs', Sync) {
            from 'src/docs/asciidoc'
            into layout.buildDirectory.dir('generated-docs')
        }
        tasks.named('asciidoctorHtml') {
            dependsOn generateDocs
        }
        '''.stripIndent()
        configureSourceSetGroovy(DEFAULT_PUBLICATION, '''
        sourceDir = layout.buildDirectory.dir('generated-docs')
        '''.stripIndent())

        when: 'the build runs on a clean project, so the generated directory does not exist at configuration time'
        final result1 = getGradleRunnerConfigCache(IS_GROOVY_DSL, [taskName]).build()

        then: 'the generated sources are converted'
        result1.task(':generateDocs').outcome == SUCCESS
        result1.task(":${taskName}").outcome == SUCCESS
        fileExists(outputDir, 'simple.html')
        result1.output.contains('Configuration cache entry stored')

        when: 'the build runs again'
        final result2 = getGradleRunnerConfigCache(IS_GROOVY_DSL, [taskName]).build()

        then: 'the configuration cache entry is reused and the task is up to date'
        result2.output.contains('Configuration cache entry reused')
        result2.task(":${taskName}").outcome == UP_TO_DATE
    }

    void 'Generated external sources are converted when the configuration cache is enabled'() {
        setup:
        final subdir = 'someSubdir'
        final otherSourceDir = new File(TEST_PROJECTS_DIR, 'resources/src/docs/asciidoc').absoluteFile
        copyTestProject('normal')
        buildFile << """
        def generateDocs = tasks.register('generateDocs', Sync) {
            from 'src/docs/asciidoc'
            into layout.buildDirectory.dir('generated-docs')
        }
        def generateExternalDocs = tasks.register('generateExternalDocs', Sync) {
            from '${getEscapedPathString(otherSourceDir.absolutePath)}'
            into layout.buildDirectory.dir('generated-external-docs')
        }
        tasks.named('asciidoctorHtml') {
            dependsOn generateDocs, generateExternalDocs
        }
        """.stripIndent()
        configureSourceSetGroovy(DEFAULT_PUBLICATION, """
        sourceDir = layout.buildDirectory.dir('generated-docs')
        externalSource {
            sourceDir = layout.buildDirectory.dir('generated-external-docs')
            sources {
                include 'simple.adoc'
            }
            into '${subdir}'
        }
        """.stripIndent())

        when: 'the build runs on a clean project, so neither generated directory exists at configuration time'
        final result1 = getGradleRunnerConfigCache(IS_GROOVY_DSL, [taskName]).build()

        then: 'the local and the external generated sources are converted'
        result1.task(":${taskName}").outcome == SUCCESS
        fileExists(outputDir, 'sample.html')
        fileExists(outputDir, 'subdir/sample2.html')
        fileExists(outputDir, "${subdir}/simple.html")
        result1.output.contains('Configuration cache entry stored')

        when: 'the build runs again'
        final result2 = getGradleRunnerConfigCache(IS_GROOVY_DSL, [taskName]).build()

        then: 'the configuration cache entry is reused and the task is up to date'
        result2.output.contains('Configuration cache entry reused')
        result2.task(":${taskName}").outcome == UP_TO_DATE
    }
}
