= Adding an external backend as an output formatter

Although the popular {asciidoctorj-name} backends are supported in this plugin suite, there is a good chance that one might want to use a backend that is not directly supported.
For this there is a special output formatter of type `AsciidoctorjGenericOutputFormatter`.

[source,groovy,role=primary]
----
import org.asciidoctor.gradle.model5.jvm.formatters.AsciidoctorjGenericOutputFormatter
import org.asciidoctor.gradle.model5.jvm.toolchains.AsciidoctorjToolchain

asciidoc {
  toolchains {
    asciidoctorj.registeredOutputFormatters {
      myBackend(AsciidoctorjGenericOutputFormatter) {
        backend = 'foo' // <.>
        attributes( foo_color : 'black') // <.>
        copyResources = false // <.>
        enforcedDocType = 'book' // <.>
        requires 'foo' // <.>
        useGem 'foo', '1.2.3' // <.>
        useModule( 'acme.foo:foo', '1.2.3') // <.>
        useModule( dependencies.project(':my-backend')) // <.>
      }
    }
  }
}
----
<.> Set the name of the backend
<.> Set the specific attributes that this backend might require.
<.> Set whether the backend should copy resources.
<.> If the backend requires a specific kind of document type, set it here, otherwise leave it alone.
<.> If one or more `requires` need to be passed to the engine, define them here.
<.> If the backend is only available as a GEM, add the name of the GEM and its version.
  To use this option, the `org.asciidoctor.jvm.gems` must be applied.
<.> If the backend is available as a JAR artifact from a Maven or Ivy repository, provide the Maven module coordinates as well as something that will resolve to a version string.
<.> If the backend is provided from the current project hierarchy, it can be referenced as a project dependency.


