= The Kroki extension

The default diagram support on {asciidoctorj-name} has always been xref:model5/asciidoctorj/diagram.adoc[{asciidoctorj-name} Diagram], but it suffers from ensuring many other components needed to be managed locally.
The Kroki extension is a great alternative and is recommended for most use cases.

[tabs]
====
Groovy::
+
--
[source,groovy]
[subs=attributes+]
.build.gradle
----
plugins {
    id 'org.asciidoctor.jvm.kroki' version '{release-version}'
}
----
--

Kotlin::
+
--
[source,kotlin]
[subs=attributes+]
.build.gradle.kts
----
plugins {
    id("org.asciidoctor.jvm.kroki") version "{release-version}"
}
----
--
====

:partials-toolchain-name: asciidoctorj
:partials-toolchain-type: AsciidoctorjToolchain
:partials-toolchain-kroki-type: AsciidoctorjKrokiExtension
:partials-package-part: jvm
include::partial$kroki-options.adoc[]

== Using Kroki with EPUB and PDF

In order to you use Kroki images with EPUB and PDF you have one of two options to have the options downloaded.

* Have Kroki download the images.
* Set the `allow-uri-read` attribute on the source set.

Both of these options affect all the publications that use the specific toolchain.
If this is not to your liking, you can create an additional `asciidoctorj` toolchain and set the Kroki setting only on that toolchain.

.Using an additional toolchain
[tabs]
====
Groovy::
+
--
[source,groovy]
[subs=attributes+]
.build.gradle
----
import org.asciidoctor.gradle.model5.jvm.toolchains.AsciidoctorjToolchain
import org.asciidoctor.gradle.model5.jvm.extensions.AsciidoctorjKrokiExtension

asciidoc {
    toolchains {
        asciidoctorj2(AsciidoctorjToolchain) {
            asciidocExtensions {
                kroki(AsciidoctorjKrokiExtension) {
                    fetchDiagrams = true
                }
            }
        }
    }

    publications {
        main {
            output 'asciidoctorj', 'html' // <.>
            output 'asciidoctorj2', 'epub' // <.>
        }
    }
}
----
<.> The HTML backend will use the links to the Kroki server.
<.> The EPUB backend will use the images downloaded by the second `asciidoctorj` toolchain.
--
====

.Setting the `allow-uri-read` for the source set
[tabs]
====
Groovy::
+
--
[source,groovy]
[subs=attributes+]
.build.gradle
----
import org.asciidoctor.gradle.model5.jvm.toolchains.AsciidoctorjToolchain
import org.asciidoctor.gradle.model5.jvm.extensions.AsciidoctorjKrokiExtension

asciidoc {
    publications {
        main {
            sourceSet {
                attributes {
                    add 'allow-uri-read', 1 // <.>
                }
            }
        }
    }
}
----
<.> Sets the attribute.
You might consider https://docs.asciidoctor.org/asciidoc/latest/directives/include-uri/#caching-uri-content[caching the content], by adding a custom extension which uses the `open-uri-cached` GEM.
--
====

It might be better to only turn that on for PDF, which is the recommended approach if you have multiple outputs on the same source set.

.Setting the `allow-uri-read` for the source set
[tabs]
====
Groovy::
+
--
[source,groovy]
[subs=attributes+]
.build.gradle
----
import org.asciidoctor.gradle.model5.jvm.formatters.AsciidoctorjPdf

asciidoc {
    toolchains {
        asciidoctorj {
            registeredOutputFormatters {
                pdf(AsciidoctorjPdf) {
                    allowUriRead = true
                }
            }
        }
    }
}
----
<.> Sets the attribute only on the PDF output formatter
You might consider https://docs.asciidoctor.org/asciidoc/latest/directives/include-uri/#caching-uri-content[caching the content], by adding a custom extension which uses the `open-uri-cached` GEM.
--
====


