plugins {
    id 'org.asciidoctor.internal.classic.groovy.project'
}

generateModuleVersions {
    basename = 'testfixtures-core'
    propertyNames ~/.+/

    additionalProperties 'offline-repo-location' : new File(rootDir,'.offline-repo').absolutePath
}

dependencies {
    implementation localGroovy()
    implementation gradleApi()
    implementation gradleTestKit()
    api libs.grolifantApi
    runtimeOnly libs.grolifantRuntime

    api libs.commonsIO
    implementation libs.jsoup
    implementation libs.cglib
    compileOnly("org.spockframework:spock-core:${agProject.versionOf('spock')}") {
        exclude group: 'org.codehaus.groovy'
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }
}
