plugins {
    id 'org.asciidoctor.internal.model5.gradle.project'
}

agProject {
    withIntegrationTests()
    withAdditionalPluginClasspath()
    configurePlugin(
            'org.asciidoctor.editorconfig',
            'Asciidoctor Editor Config Plugin',
            'Generate .asciidoctorconfig files for use by supported IDEs',
            'org.asciidoctor.gradle.model5.editorconfig.AsciidoctorEditorConfigPlugin',
            ['intellij', 'idea']
    )
}

dependencies {
    additionalPluginClasspath(project(':asciidoctor5-js-core-plugin'))
}



