= Introduction

[source,groovy,subs=+attributes]
----
import org.asciidoctor.gradle.model5.jvm.toolchains.AsciidoctorjToolchain
import org.asciidoctor.gradle.model5.jvm.formatters.AsciidoctorjHtml5
import org.asciidoctor.gradle.model5.jvm.extensions.AsciidoctorjDiagram
import org.asciidoctor.gradle.model5.js.toolchains.AsciidoctorjsNativeToolchain
import org.asciidoctor.gradle.model5.js.formatters.AsciidoctorjsDocbook

plugins {
    id 'org.asciidoctor.jvm' version '{release-version}' // <.>
    id 'org.asciidoctor.jvm.diagram' version '{release-version}'
    id 'org.asciidoctor.js' version '{release-version}'
    id 'org.asciidoctor.js.docbook' version '{release-version}'
}

asciidoc {
    toolchains { // <.>
        asciidoctorj2(AsciidoctorjToolchain) { // <.>
            registeredOutputFormatters {
                html(AsciidoctorjHtml5) {  // <.>

                }
            }
            asciidocExtensions { // <.>
                diagram(AsciidoctorjDiagram) {
                    useDitaa()
                }
            }
        }
        asciidoctorjs2(AsciidoctorjsNativeToolchain) { // <.>
            registeredOutputFormatters {
                docbook(AsciidoctorjsDocbook) { // <.>

                }
            }
        }
    }

    publications { // <.>
        main {
            sourceSet { // <.>
            }

            output('asciidoctorj', 'html') // <.>
            output('asciidoctorjs', 'docbook') // <.>
        }
    }
}
----
<.> The plugins for {asciidoctorj-name}, its diagram extension, {asciidoctorjs-name} and its DocBook output formatter.
<.> Manages toolchains.
<.> Registers a toolchain that will use `asciidoctorj`.
  If `org.asciidoctor.jvm` is applied, there will be a default toolchain called `asciidoctorj`.
<.> Create a HTML output formatter for the `asciidoctorj` toolchains.
 If `org.asciidoctor.jvm` is applied, there will be a `html` and a `docbook` output formatter.
<.> Manages extensions.

<.> Registers a toolchain that will use `asciidoctor.js`.
If `org.asciidoctor.js` is applied, there will be a default toolchain called `asciidoctorjs`.
<.> Create a DocBook output formatter for the `asciidoctorjs` toolchains.
If `org.asciidoctor.js` is applied, there will be a `html` output formatter.
The DocBook formatter will be registered if `org.asciidoctor.js.docbook` is also applied.
<.> Manages publications.
<.> Defines the sources of a publication.
<.> Defines an output.
  In this example it says HTML output should be produced using the `asciidoctorj` toolchain.
  An output refers to a valid toolchain and an output formatter on that toolchain.
<.> Multiple outputs can be listed.
  This second example says that DocBook output should be produced using the `asciidoctorjs` toolchain.

