#!/usr/bin/env bash

set -e

$(dirname $(dirname $0))/gradlew groovydoc && \
    cd $(dirname $0) && \
    ./gradlew --console=plain -q combineDocs

if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_REPO_SLUG}" == "asciidoctor/asciidoctor-gradle-plugin" ]] ; then
    set -x
    ./gradlew --console=plain :antora:publishDocs :gh-pages:publishDocs \
            -Dorg.ajoberstar.grgit.auth.username=$GITHUB_PUBLISH_USER \
            -Dorg.ajoberstar.grgit.auth.password=$GITHUB_PUBLISH_KEY \
            -Dorg.ajoberstar.grgit.auth.force=hardcoded
fi