:AsciidoctorPdfTask-url: {groovydoc-jvm}/AsciidoctorPdfTask.html
[[jvm-pdf-plugin,AsciidoctorJ PDF plugin]]
== The AsciidoctorPdf Plugin


When applying `org.asciidoctor.jvm.pdf` it creates a single task of type `org.asciidoctor.gradle.jvm.pdf.AsciidoctorPdfTask` an extension called `pdfThemes`

The default task is named `asciidoctorPdf` and is configured to:

* Output source to "${buildDir}/docs/asciidocPdf"
* Not to copy any resources to the output directory
* It will set also a default version for `asciidoctorj-pdf` artifact. To override set `asciidoctorj.pdfVersion` or `asciidoctorPdf.asciidoctorj.pdfVersion`.

The link:{AsciidoctorPdfTask-url}[AsciidoctorPdfTask] task type has the following additional methods:

[horizontal]
fontsDir:: Directory for custom PDF fonts.
  Specify a directory in any form acceptable to `project.file`. Using this instead of directly setting the `pdf-fontsdir` attribute means that Gradle will be able to check out of date status dependent on the content of this folder.
theme:: Name of the theme to use.
  Optional. When specifying a theme name it must match one registered via `pdfThemes`.

=== PDF themes

The `pdfThemes` extension allows for themes to be registered from local copies or downloaded from GitHub or GitLab and has been inspired by earlier work of {fwilhe}.

.Registering a local theme
[source,groovy]
----
pdfThemes {
    local 'basic', { // <1>
        styleDir = file('themes/basic') // <2>
        styleName = 'very-basic' // <3>
    }
}
----
<1> Local themes are registered using the `local` keyword and must be provided with a name
<2> Directory for finding the theme. Specify a directory in any form acceptable to `project.file`.
<3> Optional setting of the style name. If this is not set, the theme name provided previously will be used.

.Registering a GitHub or GitLab theme
[source,groovy]
----
include::{gradletest-snippets-jvm}/full-pdf-example/build.gradle[tags=pdf-themes]
----
<1> Specify a GitHub repository which contains one or more themes. (For GitLab replace `github` with `gitlab`).
<2> GitHub/GitLab Organisation (or user).
<3> Name of repository containing the theme(s).
<4> Relative path inside the repository to where the theme is located. If not speciified the theme is assumed to be in the root of the repository.
<5> Specify the branch
<6> Instead of a branch a tag can be used.
<7> Instead of a branch or a tag, a very specific commit can be used.

////
.Registering a GitHub or GitLab theme
[source,kotlin]
----
include::{gradletest-snippets-jvm}/full-pdf-example/build.gradle.kts[tags=pdf-themes]
----
<1> Specify a GitHub repository which contains one or more themes. (For GitLab replace `github` with `gitlab`).
<2> GitHub/GitLab Organisation (or user).
<3> Name of repository containing the theme(s).
<4> Relative path inside the repository to where the theme is located. If not speciified the theme is assumed to be in the root of the repository.
<5> Specify the branch
<6> Instead of a branch a tag can be used.
<7> Instead of a branch or a tag, a very specific commit can be used.
////

If a repository contains more than one theme, then the block will need to be repeated for each theme and the `name` and `relativePath` adjusted accordingly. Gradle will however, only downlaod the repository once.

Once registered the theme can be used wiyth and link:AsciidoctorPdfTask-url[AsciidoctorPdfTask].

[source,groovy]
----
include::{gradletest-snippets-jvm}/full-pdf-example/build.gradle[tags=pdf-themes-usage]
----
<1> Match the name to one previsouly registered in `pdfThemes`.

////
[source,kotlin]
----
include::{gradletest-snippets-jvm}/full-pdf-example/build.gradle.kts[tags=pdf-themes-usage]
----
////

=== PDF process control

There are a number of controls of how the actual conversion process will be dealt with in the JVM.

[source,groovy]
----
include::{gradletest-snippets-jvm}/full-pdf-example/build.gradle[tags=pdf-process-control]
----
<1> Log each document as it is being converted
<2> If there are multiple documetns to be converted, try to convert them in parallel.
<3> Set the preferred <<ProcessMode,processing mode>> for PDF documents. Note that Gradle might decide to use another mode when there are known compatibility issues.
<4> Set the JVM fork options for case where the process mode is `JAVA_EXEC` or `OUT_OF_PROCESS`. Any settings from link:{grolifant-api-yurl}/JavaForkOptions.html[JavaForkOptions] can be used.

////
[source,kotlin]
----
include::{gradletest-snippets-jvm}/full-pdf-example/build.gradle.kts[tags=pdf-process-control]
----
<1> Log each document as it is being converted
<2> If there are multiple documetns to be converted, try to convert them in parallel.
<3> Set the preferred <<ProcessMode,processing mode>> for PDF documents. Note that Gradle might decide to use another mode when there are known compatibility issues.
<4> Set the JVM fork options for case where the process mode is `JAVA_EXEC` or `OUT_OF_PROCESS`. Any settings from link:{grolifant-api-yurl}/JavaForkOptions.html[JavaForkOptions] can be used.
////

=== Configuring folders

Overriding defaults for directories is useful when the providd convention does not match the worflow.

[source,groovy]
----
include::{gradletest-snippets-jvm}/full-pdf-example/build.gradle[tags=pdf-folders]
----
<1> Change the source directory.
<2> Change the output directory for the final PDF.
<3> It is possible to override the base directory. Usually this is the directory of the root project, but if this is not working in a context, the freedom to make adjustments are there.
<4> Set the directory where fonts for additional PDF theming can be found.
<5> Use an intermediate working directory in order to prevent processes called by Asciidoctor writing back to the source directory.

////
[source,kotlin]
----
include::{gradletest-snippets-jvm}/full-pdf-example/build.gradle.kts[tags=pdf-folders]
----
////

=== Configuring sources

Sources are always resolved relative to the `sourceDir` property.

[source,groovy]
----
include::{gradletest-snippets-jvm}/full-pdf-example/build.gradle[tags=pdf-sources]
----
<1> Specify one of more source files to be included.
<2> A more generic form of specifying sources which takes a Gradle PatternSet
<3> Resources are items such as images which form part of the PDF processing, but are not documents themselves. They are always specified using a `PatternSet`.
<4> Clear any specific secondary sources that might already have been set as part of the PDF task's defaults.
<5> Secondary sources are entities that affect the generation of the document, but do not end up in the PDF itself. Examples include Yaml files for styling. Secondary sources are always specified as a `PatternSet`.

////
[source,kotlin]
----
include::{gradletest-snippets-jvm}/full-pdf-example/build.gradle.kts[tags=pdf-sources]
----
////

=== Configuring attributes and options

Attributes and options are inherited from the global values set, but can be augmented or even completely overridden in the task itself.

[source,groovy]
----
include::{gradletest-snippets-jvm}/full-pdf-example/build.gradle[tags=pdf-options-and-attributes]
----
<1> The task has its own `asciidoctorj` extension which has exactly the same configuration capabilities as the <<asciidoctorj-extension,global project extension>>.
<2> Remove any previous options that were set. This also removes any global options.
<3> Add options to be passed to Asciidoctorj in a hashmap form.
<4> Remove any previous attributes that were set. This also removes any global attributes.
<5> Add attributes in a hashmap form.

////
[source,kotlin]
----
include::{gradletest-snippets-jvm}/full-pdf-example/build.gradle.kts[tags=pdf-options-and-attributes]
----
////
