[appendix]
== Tips & Tricks

=== Issues with plugins that modify project.version

Plugins such as https://github.com/nebula-plugins/nebula-release-plugin[Nebula Release] and https://github.com/ajoberstar/reckon[Reckon] modify `project.version` with a non-serialisable object. This breaks the build.

The safest workaround is to set the `revnumber` attribute to a delayed evaluation of `project.version` in your build:

[source,groovy]
----
asciidoctorj {
    attributes revnumber : { project.version.toString() }
}
----

=== Pre-process and post-process

To make your own custom actions before or after asciidoctor processing, use `doFirst` and `doLast`. Check out chapters https://docs.gradle.org/current/userguide/tutorial_using_tasks.html[14] and https://docs.gradle.org/current/userguide/more_about_tasks.html[17] in the Gradle docs to learn about the various actions you can perform.

[source,groovy]
.build.gradle
----
asciidoctor.doFirst {
  // pre-process
}
asciidoctor.doLast {
  // post-process
}
----

As an example, here's how to copy the generated `index.html` file to the root of the project. This is useful in Windows systems where asciidoctor can't output directly to the root.

[source,groovy]
.build.gradle
----
asciidoctor.doLast {
    copy {
        from 'build/docs/html5'
        into "$projectDir"
        include 'index.html'
    }
}
----

=== Using Pygments source highlighter

NOTE: You need to have Python 2.x installed on a system or in a container for Pygments to work.

[source,groovy]
[subs=attributes+]
----
plugins {
  id 'org.asciidoctor.jvm.pdf' version '{revnumber}'
  id 'org.asciidoctor.jvm.gems' version '{revnumber}'
}

repositories {
    jcenter()
    ruby.gems()
}

dependencies {
  asciidoctorGems 'rubygems:pygments:1.2.1'
}

asciidoctorPdf {
  dependsOn asciidoctorGemsPrepare
  sourceDir 'docs'

  asciidoctorj {
    requires 'pygments'
    attributes 'source-highlighter' : 'pygments'
  }
}
----

=== Resolving AsciidoctorJ dependencies against a specific repository


[source,groovy]
----
include::{plugin-jvm}/test/groovy/org/asciidoctor/gradle/jvm/AsciidoctorJExtensionSpec.groovy[tags=restrict-repository,indent=0]
----
